// Deterministic daily quote — no network dependency, so every device shows the
// exact same quote on the same day (picked by day-of-year, cycles yearly).

export const QUOTES = [
  { text: "Disziplin ist die Brücke zwischen Zielen und Erfolg.", author: "Jim Rohn" },
  { text: "Motivation bringt dich in Gang. Disziplin hält dich in Bewegung.", author: "Jim Ryun" },
  { text: "Du wirst nicht jeden Tag Lust haben. Deshalb zählt Disziplin mehr als Motivation.", author: "Unbekannt" },
  { text: "Der Schmerz der Disziplin wiegt viel weniger als der Schmerz des Bedauerns.", author: "Unbekannt" },
  { text: "Erfolg ist die Summe kleiner Anstrengungen, die täglich wiederholt werden.", author: "Robert Collier" },
  { text: "Tu es nicht, weil es leicht ist. Tu es, weil es sich lohnt.", author: "Unbekannt" },
  { text: "Niemand ist zu müde für zehn Minuten mehr.", author: "David Goggins" },
  { text: "Der Unterschied zwischen dir und deinem Ziel ist meistens nur die Ausrede, die dich davon abhält.", author: "Unbekannt" },
  { text: "Du musst nicht großartig sein, um anzufangen. Aber du musst anfangen, um großartig zu werden.", author: "Zig Ziglar" },
  { text: "Was heute schwer ist, macht dich morgen stärker.", author: "Unbekannt" },
  { text: "Konsequenz schlägt Intensität.", author: "Unbekannt" },
  { text: "Kleine Schritte, jeden Tag — das ist der ganze Trick.", author: "Unbekannt" },
  { text: "Du kannst keine Abkürzung nehmen zu etwas, das die harte Arbeit wert ist.", author: "Unbekannt" },
  { text: "Der beste Zeitpunkt anzufangen war gestern. Der zweitbeste ist jetzt.", author: "Unbekannt" },
  { text: "Wer aufhört, besser zu werden, hat aufgehört, gut zu sein.", author: "Philip Rosenthal" },
  { text: "Es ist egal, wie langsam du gehst, solange du nicht stehen bleibst.", author: "Konfuzius" },
  { text: "Harte Zeiten formen starke Menschen.", author: "Unbekannt" },
  { text: "Dein einziges Limit bist du selbst.", author: "Unbekannt" },
  { text: "Träume nicht von deinem Ziel. Arbeite dafür.", author: "Unbekannt" },
  { text: "Schmerz ist temporär. Aufgeben ist für immer.", author: "Lance Armstrong" },
  { text: "Wenn es einfach wäre, würde es jeder tun.", author: "Unbekannt" },
  { text: "Du bist stärker, als dein letzter schlechter Tag dich glauben lässt.", author: "Unbekannt" },
  { text: "Der Weg entsteht beim Gehen.", author: "Franz Kafka" },
  { text: "Nicht der Berg vor dir bezwingt dich, sondern der Kiesel in deinem Schuh.", author: "Muhammad Ali" },
  { text: "Alles, was du willst, liegt auf der anderen Seite der Angst.", author: "George Addair" },
  { text: "Fokus schlägt Talent, wenn Talent nicht fokussiert ist.", author: "Unbekannt" },
  { text: "Wiederholung ist die Mutter des Könnens.", author: "Unbekannt" },
  { text: "Ein Sieg über sich selbst ist der größte aller Siege.", author: "Platon" },
  { text: "Erfolg gehört nicht den Schnellsten, sondern den Beharrlichen.", author: "Unbekannt" },
  { text: "Zähle nicht die Tage, mach die Tage zählend.", author: "Muhammad Ali" },
  { text: "Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren.", author: "Bertolt Brecht" },
  { text: "Setz dir Ziele, die dich nachts wachhalten und morgens aufstehen lassen.", author: "Unbekannt" },
  { text: "Übung macht nicht perfekt. Perfekte Übung macht perfekt.", author: "Vince Lombardi" },
  { text: "Ein bisschen mehr heute — ein ganz anderes Ergebnis morgen.", author: "Unbekannt" },
  { text: "Du musst nicht perfekt sein. Du musst nur weitermachen.", author: "Unbekannt" },
  { text: "Der Preis für Erfolg ist harte Arbeit, Hingabe und ständiger Einsatz.", author: "Vince Lombardi" },
  { text: "Vergleiche dich mit dem, der du gestern warst — nicht mit anderen.", author: "Jordan Peterson" },
  { text: "Ausdauer ist nicht die lange Rennstrecke, sondern viele kurze Rennen hintereinander.", author: "Walter Elliot" },
  { text: "Alles, was dich nicht umbringt, macht dich stärker.", author: "Friedrich Nietzsche" },
  { text: "Fange an, wo du stehst. Nutze, was du hast. Tu, was du kannst.", author: "Arthur Ashe" },
  { text: "Erfolg ist kein Zufall. Es ist harte Arbeit, Ausdauer, Lernen und vor allem Liebe zu dem, was man tut.", author: "Pelé" },
  { text: "Es geht nicht darum, ob du fällst. Es geht darum, wie oft du wieder aufstehst.", author: "Vince Lombardi" },
  { text: "Du wirst nie wissen, wie stark du bist, bis stark sein deine einzige Option ist.", author: "Bob Marley" },
  { text: "Struktur schlägt Willenskraft.", author: "Unbekannt" },
  { text: "Was du heute vermeidest, holt dich morgen doppelt ein.", author: "Unbekannt" },
  { text: "Der Körper erreicht, was der Geist glaubt.", author: "Unbekannt" },
  { text: "Klein anfangen ist besser als gar nicht anfangen.", author: "Unbekannt" },
  { text: "Gewohnheiten formen dein Leben, lange bevor Ergebnisse sichtbar sind.", author: "Unbekannt" },
  { text: "Jeder Experte war einmal ein Anfänger.", author: "Robin Sharma" },
  { text: "Du hast heute die Wahl: Ausreden oder Fortschritt.", author: "Unbekannt" },
  { text: "Konzentriere dich auf den Prozess, nicht auf das Ergebnis.", author: "Unbekannt" },
  { text: "Die beste Investition ist die in dich selbst.", author: "Warren Buffett" },
  { text: "Was zählt, ist nicht die Größe des Hundes im Kampf, sondern die Größe des Kampfes im Hund.", author: "Mark Twain (zugeschrieben)" },
  { text: "Wer nichts riskiert, riskiert noch mehr.", author: "Erica Jong" },
  { text: "Der Unterschied zwischen unmöglich und möglich liegt in der Entschlossenheit eines Menschen.", author: "Tommy Lasorda" },
  { text: "Es ist nicht, wer dich aufhält. Es ist, wer du dir erlaubst zu sein.", author: "C. JoyBell C." },
  { text: "Jeder Meister war einmal ein Desaster.", author: "T. Harv Eker" },
  { text: "Zweifel tötet mehr Träume als Scheitern jemals wird.", author: "Suzy Kassem" },
  { text: "Ausreden sind die Nägel, mit denen ein Haus des Scheiterns gebaut wird.", author: "Unbekannt" },
  { text: "Konstanz verwandelt kleine Anstrengungen in große Ergebnisse.", author: "Unbekannt" },
  { text: "Du brauchst keine perfekten Bedingungen — nur den nächsten Schritt.", author: "Unbekannt" },
  { text: "Diszipliniere dich selbst, damit es niemand anderes tun muss.", author: "John Wooden" },
  { text: "Wachstum beginnt am Ende deiner Komfortzone.", author: "Unbekannt" },
  { text: "Es gibt keinen Aufzug zum Erfolg. Du musst die Treppe nehmen.", author: "Unbekannt" },
  { text: "Wer aufgibt, gewinnt nie. Wer gewinnt, gibt nie auf.", author: "Vince Lombardi" },
  { text: "Sei stärker als deine stärkste Ausrede.", author: "Unbekannt" },
  { text: "Ein Ziel ohne Plan ist nur ein Wunsch.", author: "Antoine de Saint-Exupéry" },
  { text: "Träume groß. Fang klein an. Handle jetzt.", author: "Robin Sharma" },
  { text: "Die Reise von tausend Meilen beginnt mit einem einzigen Schritt.", author: "Laozi" },
  { text: "Es kommt nicht darauf an, wie hart du triffst. Es kommt darauf an, wie hart du getroffen werden kannst und weitermachst.", author: "Rocky Balboa" },
  { text: "Bau dir Gewohnheiten, die dich stolz machen, wenn du zurückblickst.", author: "Unbekannt" },
  { text: "Erfolg ist, wenn Vorbereitung auf Gelegenheit trifft.", author: "Seneca" },
  { text: "Wer will, findet Wege. Wer nicht will, findet Gründe.", author: "Unbekannt" },
  { text: "Nichts wird funktionieren, wenn du es nicht tust.", author: "Maya Angelou" },
  { text: "Verantwortung ist der Preis der Größe.", author: "Winston Churchill" },
  { text: "Der Schmerz, den du heute fühlst, ist die Stärke, die du morgen spürst.", author: "Unbekannt" },
  { text: "Beständigkeit ist das, was aus Können Meisterschaft macht.", author: "Unbekannt" },
  { text: "Man muss die Zähne zusammenbeißen und weitergehen. Der Erfolg kommt zu dem, der handelt.", author: "Conrad Hilton" },
  { text: "Du wirst es nicht bereuen, hart gearbeitet zu haben.", author: "Unbekannt" },
  { text: "Vertrau dem Prozess. Die Ergebnisse kommen von selbst.", author: "Unbekannt" },
  { text: "Der Preis, den du heute zahlst, ist der Erfolg, den du morgen erntest.", author: "Unbekannt" },
  { text: "Große Dinge werden nicht durch Impuls getan, sondern durch eine Reihe kleiner Dinge, die zusammengefügt sind.", author: "Vincent van Gogh" },
  { text: "Deine Zukunft wird von dem geschaffen, was du heute tust, nicht von dem, was du morgen tust.", author: "Robert Kiyosaki" },
  { text: "Härte ist eine Entscheidung, keine Eigenschaft.", author: "Unbekannt" },
  { text: "Der Test wartet nicht auf deine Motivation. Also warte du nicht auf sie.", author: "Unbekannt" },
  { text: "Wer heute nicht übt, muss morgen umso mehr aufholen.", author: "Unbekannt" },
  { text: "Jede Wiederholung zählt — im Gym wie im Lernen.", author: "Unbekannt" },
  { text: "Zeig auf, auch wenn es sich nicht nach viel anfühlt. Es fühlt sich nie nach viel an, bis es plötzlich viel ist.", author: "Unbekannt" },
  { text: "Der Testwert 93 ist kein Zufall — er ist das Ergebnis von hundert kleinen Sessions.", author: "Unbekannt" },
  { text: "Zwischen Reiz und Reaktion liegt ein Raum. In diesem Raum liegt unsere Macht zu wählen.", author: "Viktor Frankl" },
  { text: "Was du wiederholt tust, ist das, was du wirklich bist.", author: "Aristoteles (zugeschrieben)" },
  { text: "Der Kopf gibt zuerst auf — der Körper kann mehr, als du denkst.", author: "Unbekannt" },
  { text: "Erfolg ist ein Nebenprodukt harter Arbeit und Ausdauer.", author: "Colin Powell" },
  { text: "Mach heute etwas, wofür dein zukünftiges Ich dankbar ist.", author: "Sean Patrick Flanery" },
  { text: "Progress, nicht Perfektion.", author: "Unbekannt" },
  { text: "Egal wie langsam — Hauptsache, du bleibst dran.", author: "Unbekannt" },
  { text: "Der einzig schlechte Workout ist der, den du nicht gemacht hast.", author: "Unbekannt" },
  { text: "Am Ende zählt nicht, wie oft du gefallen bist, sondern wie oft du weitergemacht hast.", author: "Unbekannt" },
  { text: "Die Disziplin, die du heute aufbringst, ist die Freiheit, die du morgen hast.", author: "Jocko Willink" },
  { text: "Du musst nicht extrem sein, nur konsequent.", author: "Unbekannt" },
  { text: "Kleine Gewohnheiten schlagen große Absichten.", author: "James Clear" },
  { text: "Der Unterschied zwischen wer du bist und wer du sein willst, ist das, was du tust.", author: "Unbekannt" },
  { text: "Miss deinen Fortschritt in Wochen, nicht in Tagen.", author: "Unbekannt" },
  { text: "Ein guter Plan heute ist besser als ein perfekter Plan morgen.", author: "George S. Patton" },
  { text: "Du wirst nicht durch Zufall besser — du wirst besser durch Wiederholung.", author: "Unbekannt" },
  { text: "Die Latte liegt dort, wo du sie hinlegst.", author: "Unbekannt" },
  { text: "Zeig bis zum Ende Einsatz — der Rest ergibt sich.", author: "Unbekannt" },
  { text: "Bequemlichkeit ist der Feind des Fortschritts.", author: "Unbekannt" },
  { text: "Was zählt, ist, was du tust, wenn dir niemand zusieht.", author: "Unbekannt" },
  { text: "Übe, bis du es nicht mehr falsch machen kannst.", author: "Unbekannt" },
  { text: "Erfolg ist die Fähigkeit, von Misserfolg zu Misserfolg zu gehen, ohne die Begeisterung zu verlieren.", author: "Winston Churchill" },
  { text: "Deine Grenzen sind oft nur Geschichten, die du dir selbst erzählst.", author: "Unbekannt" },
  { text: "Heute ist ein guter Tag für einen guten Tag.", author: "Unbekannt" },
  { text: "Ein bisschen besser als gestern reicht.", author: "Unbekannt" },
  { text: "Wer nicht plant, plant zu scheitern.", author: "Benjamin Franklin (zugeschrieben)" },
  { text: "Konzentrier dich auf das, was du kontrollieren kannst.", author: "Epiktet" },
  { text: "Deine Zukunft hört jetzt zu.", author: "Unbekannt" },
  { text: "Die Ziegel des Erfolgs sind aus Wiederholung gebrannt.", author: "Unbekannt" },
  { text: "Am schwersten ist der erste Schritt — danach trägt dich die Bewegung.", author: "Unbekannt" },
  { text: "Du gewinnst nicht jeden Tag. Aber du kannst jeden Tag daran arbeiten.", author: "Unbekannt" },
  { text: "Fortschritt ist unmöglich ohne Veränderung.", author: "George Bernard Shaw" },
  { text: "Wer stehen bleibt, wird überholt.", author: "Unbekannt" },
];

function dayOfYear(d) {
  const start = new Date(d.getFullYear(), 0, 0);
  const diff = d - start;
  return Math.floor(diff / 86400000);
}

export function getDailyQuote(date = new Date()) {
  const idx = dayOfYear(date) % QUOTES.length;
  return QUOTES[idx];
}
